version: "3.9"

services:
  server:
    build: .
    # restart: always # What to do if container crashes
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/server

  # client:
  #   build: ./client
  #   restart: always # What to do if container crashes
  #   ports:
  #     - 3001:3001
  # volumes:
  #   - ./client:/server/client
