version: "3.1"

services:
  server:
    build: ./server
    restart: always # What to do if container crashes
    ports:
      - 3000:3000

  client:
    build: ./client
    restart: always # What to do if container crashes
    ports:
      - 3001:3001
