version: "3.1"

services:
  server:
    build: .
    restart: always # What to do if container crashes
    ports:
      - 3000:3000
    volumes:
      - .:/server

  client:
    build: ./client
    restart: always # What to do if container crashes
    ports:
      - 3001:3001
    # volumes:
    #   - ./client:/server/client
