version: "3.9"

services:
  server:
    build: ./server
    restart: always # What to do if container crashes
    container_name: server_c
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
  client:
    build: ./client
    restart: always # What to do if container crashes
    container_name: client_c
    ports:
      - "3001:3001"
    # volumes:
    # - ./client:/app
    # stdin_open: true
